-- MySQL Script generated by MySQL Workbench
-- seg 29 nov 2021 22:15:00
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  `Usuario` VARCHAR(45) NULL,
  `E-mail` VARCHAR(45) NULL,
  `Senha` VARCHAR(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_postagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_postagem` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Data` DATE NULL,
  `TituloP` VARCHAR(45) NULL,
  `Postagem` VARCHAR(1000) NULL,
  `id_postagem` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_postagem_idx` (`id_postagem` ASC) VISIBLE,
  CONSTRAINT `fk_tb_postagem`
    FOREIGN KEY (`id_postagem`)
    REFERENCES `mydb`.`tb_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_tema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_tema` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Livros` VARCHAR(45) NULL,
  `Musicas` VARCHAR(45) NULL,
  `Filmes` VARCHAR(45) NULL,
  `Séries` VARCHAR(45) NULL,
  `Games` VARCHAR(45) NULL,
  `id_tema1` INT NOT NULL,
  `id_tema2` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_tema_1_idx` (`id_tema1` ASC) VISIBLE,
  INDEX `fk_tb_tema_2_idx` (`id_tema2` ASC) VISIBLE,
  CONSTRAINT `fk_tb_tema_1`
    FOREIGN KEY (`id_tema1`)
    REFERENCES `mydb`.`tb_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_tema_2`
    FOREIGN KEY (`id_tema2`)
    REFERENCES `mydb`.`tb_postagem` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
